const fs = require('fs');
const path = 'src/app/intelligence/expedicao/page.tsx';
let content = fs.readFileSync(path, 'utf8');

const map = {
  'ExpediÃƒÆ’Ã‚Â§ÃƒÆ’Ã‚Â£o': 'Expedição',
  'ExpediÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â§ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â£o': 'Expedição',
  'AÃƒÆ’Ã‚Â§ÃƒÆ’Ã‚Âµes': 'Ações',
  'JoÃƒÆ’Ã‚Â£o': 'João',
  'ConstruÃƒÆ’Ã‚Â§ÃƒÆ’Ã‚Âµes': 'Construções',
  'SeparaÃƒÆ’Ã‚Â§ÃƒÆ’Ã‚Â£o': 'Separação',
  'SeparaÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â§ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â£o': 'Separação',
  'MÃƒÆ’Ã‚Â©dia': 'Média',
  'TrÃƒÆ’Ã‚Â¢nsito': 'Trânsito',
  'SÃƒÆ’Ã‚Â£o': 'São',
  'MetalÃƒÆ’Ã‚Âºrgica': 'Metalúrgica',
  'SaÃƒÆ’Ã‚Âda': 'Saída',
  'NÃƒÆ’Ã‚Âºmero': 'Número',
  'MunicÃƒÆ’Ã‚Âpio': 'Município',
  'EndereÃƒÆ’Ã‚Â§o': 'Endereço',
  'EndereÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â§o': 'Endereço',
  'obrigatÃƒÆ’Ã‚Â³rios': 'obrigatórios',
  'obrigatÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â³rios': 'obrigatórios',
  'necessÃƒÆ’Ã‚Â¡rios': 'necessários',
  'necessÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¡rios': 'necessários',
  'EXPEDIÃƒÆ’Ã¢â‚¬Â¡ÃƒÆ’Ã†â€™O': 'EXPEDIÇÃO',
  'EXPEDIÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢O': 'EXPEDIÇÃO',
  'PeÃƒÆ’Ã‚Â§as': 'Peças',
  'peÃƒÆ’Ã‚Â§as': 'peças',
  'CÃƒÆ’Ã‚Â³digo': 'Código',
  'CÃƒÂ³digo': 'Código',
  'DescriÃƒÆ’Ã‚Â§ÃƒÆ’Ã‚Â£o': 'Descrição',
  'DescriÃƒÂ§ÃƒÂ£o': 'Descrição',
  'ExpediÃƒÂ§ÃƒÂ£o': 'Expedição',
  'TrÃƒÂ¢nsito': 'Trânsito',
  'SaÃƒÂda': 'Saída',
  'AÃƒÂ§ÃƒÂµes': 'Ações',
  'SÃƒÂ£o': 'São',
  'JoÃƒÂ£o': 'João',
  'ConstruÃƒÂ§ÃƒÂµes': 'Construções',
  'SeparaÃƒÂ§ÃƒÂ£o': 'Separação',
  'MÃƒÂ©dia': 'Média',
  'MetalÃƒÂºrgica': 'Metalúrgica',
  'NÃƒÂºmero': 'Número',
  'MunicÃƒÂpio': 'Município',
  'EndereÃƒÂ§o': 'Endereço',
  'obrigatÃƒÂ³rios': 'obrigatórios',
  'necessÃƒÂ¡rios': 'necessários',
  'EXPEDIÃƒâ€¡Ãƒâ€ O': 'EXPEDIÇÃO',
  'EXPEDIǟO': 'EXPEDIÇÃO',
  'Expediǜo': 'Expedição',
  'Sada': 'Saída',
  'Aǜes': 'Ações',
  'Mǟdia': 'Média',
  'Trǟnsito': 'Trânsito',
  'Sǟo': 'São',
  'Cdigo': 'Código',
  'Descriǜo': 'Descrição',
  'peas': 'peças',
  'Peas': 'Peças',
  'Joǟo': 'João',
  'Construǜes': 'Construções',
  'Separaǜo': 'Separação',
  'Metalrgica': 'Metalúrgica',
  'Nmero': 'Número',
  'Municpio': 'Município',
  'Endereo': 'Endereço',
  'obrigatrios': 'obrigatórios',
  'necessrios': 'necessários'
};

for (const [bad, good] of Object.entries(map)) {
  content = content.split(bad).join(good);
}

fs.writeFileSync(path, content, 'utf8');
